name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install goole test
      run: vcpkg install gtest
    - name: configure
      run: cmake -Bbuild
    - name: make
      run: make -C build
    - name: make check
      run: make -C build test
